{% set name = "brainreg" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainreg-{{ version }}.tar.gz
  sha256: 90e2a660d499f0357b83272beb1557864cbe624099079451ad27ebb5fd36e5aa

build:
  entry_points:
    - brainreg = brainreg.cli:main
  noarch: python
  script:
    # Remove niftyreg binaries in the PyPI distribution as we should depend on
    # niftyreg as already packaged in conda-forge
    - rm -r brainreg/bin  # [not win]
    - rd /s /q "brainreg/bin"  # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bg-atlasapi
    - bg-space
    - niftyreg
    - numpy
    - configparser
    - scikit-image
    - multiprocessing-logging
    - configobj
    - slurmio
    - imio
    - fancylog
    - imlib >=0.0.26

test:
  imports:
    - brainreg
  commands:
    - pip check
    - brainreg --help
  requires:
    - pip

about:
  summary: Automated 3D brain registration
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://docs.brainglobe.info/brainreg/introduction

extra:
  recipe-maintainers:
    - adamltyson
